"""Random forest rehospitalisation prediction.

By default this evaluates the forest on the full baseline feature set from
``build_features()`` so it is independent from the logistic regression model.
If you want a controlled apples-to-apples comparison, pass a predictor list
file generated by the logistic script.

Outputs are written to ``model_outputs/rf/``.
"""

from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    brier_score_loss,
    log_loss,
    roc_auc_score,
)
from sklearn.model_selection import StratifiedKFold

from hf_ml_features import build_features

sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parent
OUT_DIR = ROOT / "model_outputs" / "rf"
OUT_DIR.mkdir(parents=True, exist_ok=True)

LOGREG_DIR = ROOT / "model_outputs" / "logreg"


def load_predictors(path: Path | None) -> list[str]:
    """Load a feature list from disk, returning an empty list if unavailable."""
    if path is None or not path.exists():
        return []
    text = path.read_text(encoding="utf-8").splitlines()
    return [t.strip() for t in text if t.strip()]


def resolve_feature_set(
    baseline_columns: list[str],
    predictor_file: Path | None,
) -> tuple[list[str], str]:
    """Choose the random forest feature set.

    Returns:
        feature_names, source_label
    """
    candidate = load_predictors(predictor_file)
    if candidate:
        kept = [c for c in candidate if c in baseline_columns]
        if kept:
            return kept, f"shared predictor file: {predictor_file}"
    return baseline_columns, "full baseline feature set"


def cross_validate_random_forest(
    X: pd.DataFrame,
    y: pd.Series,
    n_splits: int = 5,
    seed: int = 42,
) -> pd.DataFrame:
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)
    rows = []
    for fold, (tr, te) in enumerate(skf.split(X, y), start=1):
        Xtr, Xte = X.iloc[tr], X.iloc[te]
        ytr, yte = y.iloc[tr], y.iloc[te]

        rf = RandomForestClassifier(
            n_estimators=800,
            random_state=seed,
            class_weight="balanced_subsample",
            min_samples_leaf=3,
            max_features="sqrt",
            n_jobs=-1,
        )
        rf.fit(Xtr, ytr)
        prob = rf.predict_proba(Xte)[:, 1]
        pred = (prob >= 0.5).astype(int)
        rows.append(
            {
                "fold": fold,
                "n_train": len(tr),
                "n_test": len(te),
                "AUC": roc_auc_score(yte, prob),
                "accuracy": accuracy_score(yte, pred),
                "log_loss": log_loss(yte, prob, labels=[0, 1]),
                "brier": brier_score_loss(yte, prob),
            }
        )
    return pd.DataFrame(rows)


def model_summary_row(name: str, model: RandomForestClassifier, n_features: int) -> dict:
    return {
        "model": name,
        "n_trees": int(model.n_estimators),
        "n_features": int(n_features),
        "max_features": model.max_features,
        "min_samples_leaf": int(model.min_samples_leaf),
        "class_weight": str(model.class_weight),
        "bootstrap": bool(model.bootstrap),
        "oob_score": float(model.oob_score_) if getattr(model, "oob_score_", None) is not None else np.nan,
    }


def feature_table(model: RandomForestClassifier, feature_names: list[str]) -> pd.DataFrame:
    out = (
        pd.DataFrame(
            {
                "feature": feature_names,
                "importance": model.feature_importances_,
            }
        )
        .sort_values("importance", ascending=False)
        .reset_index(drop=True)
    )
    out.insert(0, "rank", np.arange(1, len(out) + 1))
    out["cumulative_importance"] = out["importance"].cumsum()
    return out


def build_report(
    cv: pd.DataFrame,
    feature_source: str,
    feature_names: list[str],
    summary: pd.DataFrame,
    importance: pd.DataFrame,
) -> str:
    buf = io.StringIO()
    print("Random forest rehospitalisation prediction", file=buf)
    print("=" * 70, file=buf)
    print(f"Feature set: {feature_source}", file=buf)
    print(f"Predictors used ({len(feature_names)}): {', '.join(feature_names)}\n", file=buf)
    print("Model summary", file=buf)
    print("-" * 70, file=buf)
    print(summary.to_string(index=False, float_format=lambda v: f"{v:.4f}"), file=buf)
    print("\nFeature importance table", file=buf)
    print("-" * 70, file=buf)
    print(importance.to_string(index=False, float_format=lambda v: f"{v:.4f}"), file=buf)
    print("5-fold stratified cross-validation", file=buf)
    print("-" * 70, file=buf)
    print(cv.to_string(index=False, float_format=lambda v: f"{v:.4f}"), file=buf)
    means = cv[["AUC", "accuracy", "log_loss", "brier"]].mean()
    sds = cv[["AUC", "accuracy", "log_loss", "brier"]].std()
    print("\nMean +/- SD across folds:", file=buf)
    for metric in means.index:
        print(f"  {metric:<10s}: {means[metric]:.4f} +/- {sds[metric]:.4f}", file=buf)
    return buf.getvalue()


def main() -> None:
    parser = argparse.ArgumentParser(description="Fit and evaluate a random forest.")
    parser.add_argument(
        "--predictors-file",
        type=Path,
        default=None,
        help=(
            "Optional text file with one predictor per line. If omitted, the model "
            "uses the full baseline feature set."
        ),
    )
    args = parser.parse_args()

    feat = build_features()
    y = feat["REHOSPITAL"].astype(int)
    X_all = feat.drop(columns="REHOSPITAL")

    feature_names, feature_source = resolve_feature_set(
        baseline_columns=list(X_all.columns),
        predictor_file=args.predictors_file,
    )
    X = X_all[feature_names].copy()

    cv = cross_validate_random_forest(X, y, n_splits=5, seed=42)
    cv.to_csv(OUT_DIR / "cv_5fold.csv", index=False)

    rf_full = RandomForestClassifier(
        n_estimators=800,
        random_state=42,
        class_weight="balanced_subsample",
        min_samples_leaf=3,
        max_features="sqrt",
        bootstrap=True,
        oob_score=True,
        n_jobs=-1,
    )
    rf_full.fit(X, y)
    summary = pd.DataFrame([model_summary_row("rf_full", rf_full, len(feature_names))])
    imp = feature_table(rf_full, feature_names)

    summary.to_csv(OUT_DIR / "model_summary.csv", index=False)
    imp.to_csv(OUT_DIR / "feature_importance.csv", index=False)

    (OUT_DIR / "used_predictors.txt").write_text(
        "\n".join(feature_names) + "\n", encoding="utf-8"
    )
    report = build_report(
        cv=cv,
        feature_source=feature_source,
        feature_names=feature_names,
        summary=summary,
        importance=imp,
    )
    (OUT_DIR / "report.txt").write_text(report, encoding="utf-8")
    print(report)


if __name__ == "__main__":
    main()
