"""Experimental logistic regression using Main_Data + LABS + ECHO."""

from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, brier_score_loss, log_loss, roc_auc_score
from sklearn.model_selection import StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from hf_experimental_features import (
    ROOT,
    build_experimental_frames,
    load_selected_feature_names,
    select_feature_frame,
)

sys.stdout.reconfigure(encoding="utf-8")

OUT_DIR = ROOT / "model_outputs" / "experimental_lr"
PVAL_DIR = ROOT / "model_outputs" / "experimental_pvalues"
OUT_DIR.mkdir(parents=True, exist_ok=True)
PVAL_DIR.mkdir(parents=True, exist_ok=True)


def cross_validate_sklearn_logreg(
    X: pd.DataFrame, y: pd.Series, n_splits: int = 5, seed: int = 42
) -> pd.DataFrame:
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)
    rows = []
    pipe = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("logreg", LogisticRegression(max_iter=3000, solver="liblinear")),
        ]
    )
    for fold, (tr, te) in enumerate(skf.split(X, y), start=1):
        Xtr, Xte = X.iloc[tr], X.iloc[te]
        ytr, yte = y.iloc[tr], y.iloc[te]
        pipe.fit(Xtr, ytr)
        prob = pipe.predict_proba(Xte)[:, 1]
        pred = (prob >= 0.5).astype(int)
        rows.append(
            {
                "fold": fold,
                "n_train": len(tr),
                "n_test": len(te),
                "AUC": roc_auc_score(yte, prob),
                "accuracy": accuracy_score(yte, pred),
                "log_loss": log_loss(yte, prob, labels=[0, 1]),
                "brier": brier_score_loss(yte, prob),
            }
        )
    return pd.DataFrame(rows)


def model_summary_row(name: str, model: LogisticRegression, n_features: int) -> dict:
    return {
        "model": name,
        "n_features": int(n_features),
        "solver": model.solver,
        "penalty": model.penalty,
        "C": float(model.C),
        "max_iter": int(model.max_iter),
        "class_weight": str(model.class_weight),
    }


def coef_table(feature_names: list[str], model: LogisticRegression) -> pd.DataFrame:
    coefs = model.coef_.ravel()
    out = pd.DataFrame(
        {
            "feature": feature_names,
            "coef_scaled": coefs,
            "odds_ratio_per_1SD": np.exp(coefs),
        }
    )
    return out.sort_values("odds_ratio_per_1SD", ascending=False).reset_index(drop=True)


def build_report(
    use_all: bool,
    selected: pd.DataFrame,
    summary: pd.DataFrame,
    coefficients: pd.DataFrame,
    cv: pd.DataFrame,
) -> str:
    buf = io.StringIO()
    print("Experimental logistic regression - Main_Data + LABS + ECHO", file=buf)
    print("=" * 70, file=buf)
    print(f"Feature mode: {'all imputed features' if use_all else 'screened features'}", file=buf)
    print(f"Selected features: {len(selected)}", file=buf)
    print("\nSelected features", file=buf)
    print("-" * 70, file=buf)
    if selected.empty:
        print("No features passed screening.", file=buf)
    else:
        print(selected.to_string(index=False, float_format=lambda v: f"{v:.4f}"), file=buf)
    print("\nModel summary", file=buf)
    print("-" * 70, file=buf)
    print(summary.to_string(index=False, float_format=lambda v: f"{v:.4f}"), file=buf)
    print("\nCoefficients", file=buf)
    print("-" * 70, file=buf)
    print(coefficients.to_string(index=False, float_format=lambda v: f"{v:.4f}"), file=buf)
    print("\n5-fold stratified cross-validation", file=buf)
    print("-" * 70, file=buf)
    print(cv.to_string(index=False, float_format=lambda v: f"{v:.4f}"), file=buf)
    means = cv[["AUC", "accuracy", "log_loss", "brier"]].mean()
    sds = cv[["AUC", "accuracy", "log_loss", "brier"]].std()
    print("\nMean +/- SD across folds:", file=buf)
    for metric in means.index:
        print(f"  {metric:<10s}: {means[metric]:.4f} +/- {sds[metric]:.4f}", file=buf)
    return buf.getvalue()


def main() -> None:
    parser = argparse.ArgumentParser(description="Experimental logistic regression.")
    parser.add_argument(
        "--use-all-features",
        action="store_true",
        help="Fit on the full imputed feature matrix instead of the screened subset.",
    )
    parser.add_argument(
        "--selected-features-file",
        type=Path,
        default=PVAL_DIR / "selected_features.csv",
        help="CSV generated by experimental_pvalues.py with a feature_name column.",
    )
    args = parser.parse_args()

    raw_frame, imputed_frame, y, meta = build_experimental_frames()

    if args.use_all_features:
        feature_names = load_selected_feature_names(args.selected_features_file, imputed_frame, use_all=True)
        selected_for_report = pd.DataFrame(
            {
                "sheet": ["ALL"] * len(feature_names),
                "base_name": feature_names,
                "feature_name": feature_names,
                "representation": ["all"] * len(feature_names),
                "test_type": ["n/a"] * len(feature_names),
                "p_value": [np.nan] * len(feature_names),
            }
        )
    else:
        selected = pd.read_csv(args.selected_features_file) if args.selected_features_file.exists() else pd.DataFrame()
        feature_names = load_selected_feature_names(args.selected_features_file, imputed_frame, use_all=False)
        selected_for_report = selected

    X = select_feature_frame(imputed_frame, feature_names).drop(columns="historyID")
    cv = cross_validate_sklearn_logreg(X, y, n_splits=5, seed=42)
    cv.to_csv(OUT_DIR / "cv_5fold.csv", index=False)

    pipe = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("logreg", LogisticRegression(max_iter=3000, solver="liblinear")),
        ]
    )
    pipe.fit(X, y)
    lr: LogisticRegression = pipe.named_steps["logreg"]

    summary = pd.DataFrame([model_summary_row("experimental_lr", lr, len(feature_names))])
    coef = coef_table(feature_names, lr)

    summary.to_csv(OUT_DIR / "model_summary.csv", index=False)
    coef.to_csv(OUT_DIR / "coefficients.csv", index=False)
    (OUT_DIR / "selected_features.txt").write_text("\n".join(feature_names) + "\n", encoding="utf-8")

    report = build_report(args.use_all_features, selected_for_report, summary, coef, cv)
    (OUT_DIR / "report.txt").write_text(report, encoding="utf-8")
    print(report)


if __name__ == "__main__":
    main()
